export const FETCH_HOME_MEALS_START = 'FETCH_HOME_MEALS_START';
export const FETCH_HOME_MEALS_SUCCESS = 'FETCH_HOME_MEALS_SUCCESS';
export const FETCH_HOME_MEALS_FAIL = 'FETCH_HOME_MEALS_FAIL';
export const SET_HOME_TOTAL_PAGE = 'SET_HOME_TOTAL_PAGE';
export const SET_HOME_CURRENT_PAGE = 'SET_HOME_CURRENT_PAGE';

export const FETCH_HOME_TOP_SEARCH_START = 'FETCH_HOME_TOP_SEARCH_START';
export const FETCH_HOME_TOP_SEARCH_SUCCESS = 'FETCH_HOME_TOP_SEARCH_SUCCESS';
export const FETCH_HOME_TOP_SEARCH_FAIL = 'FETCH_HOME_TOP_SEARCH_FAIL';

export const OPEN_INGREDIENT_MODAL = 'OPEN_INGREDIENT_MODAL';
export const CLOSE_INGREDIENT_MODAL = 'CLOSE_INGREDIENT_MODAL';
export const SET_CURRENT_INGREDIENT_ID = 'SET_CURRENT_INGREDIENT_ID';
export const FETCH_INGREDIENTS_START = 'FETCH_INGREDIENTS_START';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const INCREASE_MEAL_QUANTITY = 'INCREASE_MEAL_QUANTITY';
export const RELOAD_FAVORITES_DATA = 'RELOAD_FAVORITES_DATA';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
